# Generated by Django 4.1.7 on 2023-03-22 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HBLManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hbl_id", models.IntegerField()),
                ("name", models.CharField(max_length=64)),
                ("email", models.EmailField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="HBLTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_id", models.IntegerField()),
                ("name", models.CharField(max_length=64)),
                ("yahoo_team_key", models.CharField(max_length=20)),
                (
                    "manager",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team",
                        to="hbl.hblmanager",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HBLProspect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("yahoo_player_key", models.CharField(max_length=20, null=True)),
                ("team_name", models.CharField(max_length=30, null=True)),
                (
                    "primary_position",
                    models.CharField(
                        choices=[
                            ("C", "Catcher"),
                            ("1B", "First Base"),
                            ("2B", "Second Base"),
                            ("3B", "Third Base"),
                            ("SS", "Shortstop"),
                            ("LF", "Left Field"),
                            ("CF", "Center Field"),
                            ("RF", "Right Field"),
                            ("Util", "Util"),
                            ("P", "Pitcher"),
                        ],
                        default="Util",
                        max_length=4,
                    ),
                ),
                ("player_status", models.CharField(max_length=10, null=True)),
                (
                    "hbl_team",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prospects_team",
                        to="hbl.hblteam",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HBLPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_id", models.IntegerField()),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("yahoo_player_key", models.CharField(max_length=20)),
                ("team_name", models.CharField(max_length=30, null=True)),
                (
                    "primary_position",
                    models.CharField(
                        choices=[
                            ("C", "Catcher"),
                            ("1B", "First Base"),
                            ("2B", "Second Base"),
                            ("3B", "Third Base"),
                            ("SS", "Shortstop"),
                            ("LF", "Left Field"),
                            ("CF", "Center Field"),
                            ("RF", "Right Field"),
                            ("Util", "Util"),
                            ("P", "Pitcher"),
                        ],
                        default="Util",
                        max_length=4,
                    ),
                ),
                (
                    "eligible_positions",
                    models.CharField(
                        default=models.CharField(
                            choices=[
                                ("C", "Catcher"),
                                ("1B", "First Base"),
                                ("2B", "Second Base"),
                                ("3B", "Third Base"),
                                ("SS", "Shortstop"),
                                ("LF", "Left Field"),
                                ("CF", "Center Field"),
                                ("RF", "Right Field"),
                                ("Util", "Util"),
                                ("P", "Pitcher"),
                            ],
                            default="Util",
                            max_length=4,
                        ),
                        max_length=20,
                    ),
                ),
                ("keeper_cost_current", models.IntegerField(default=0)),
                ("keeper_cost_next", models.IntegerField(default=0)),
                (
                    "hbl_team",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team",
                        to="hbl.hblteam",
                    ),
                ),
                (
                    "previous_hbl_team",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="previous_team",
                        to="hbl.hblteam",
                    ),
                ),
            ],
        ),
    ]
