# Generated by Django 4.1.7 on 2023-03-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hbl", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hblplayer",
            name="player_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="hblplayer",
            name="yahoo_player_key",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
