# Generated by Django 4.1.7 on 2023-03-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hbl", "0002_alter_null_condition"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hblplayer",
            old_name="eligible_positions",
            new_name="display_positions",
        ),
        migrations.AddField(
            model_name="hblplayer",
            name="player_status",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="hblplayer",
            name="seasons_on_team",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="hblplayer",
            name="keeper_cost_next",
            field=models.IntegerField(default=1),
        ),
    ]
