# Generated by Django 4.1.7 on 2023-04-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hbl", "0003_rename_eligible_positions_hblplayer_display_positions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hblteam",
            name="name",
            field=models.CharField(
                choices=[
                    ("ARGON_CONCLUSIONS", "AC"),
                    ("BOTTOM_OF_THE_LINEUP_CARD", "BotLC"),
                    ("CVILLE_STRANGERS", "CS"),
                    ("DIGITAL_SPACE_LOOP", "DSL"),
                    ("JAY_AND_BOBS_BOYS", "JBB"),
                    ("JIM_WOHLFORD_CLONES", "JWC"),
                    ("LITTLE_GIANTS_II", "LGII"),
                    ("MGS_WONDERBOYS", "MGWB"),
                    ("THE_STORAGE_JARS", "SJ"),
                    ("WABASH_GOATS", "WG"),
                ],
                max_length=25,
            ),
        ),
    ]
