# Generated by Django 4.1.7 on 2023-04-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hbl", "0004_alter_hblteam_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="hblmanager",
            name="guid",
            field=models.CharField(default=None, max_length=64, null=True),
        ),
    ]
