# Generated by Django 4.1.7 on 2023-04-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hbl", "0005_hblmanager_guid"),
    ]

    operations = [
        migrations.AddField(
            model_name="hblplayer",
            name="four_keeper_cost",
            field=models.BooleanField(default=False),
        ),
    ]
