# Generated by Django 4.1.7 on 2023-04-28 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hbl", "0006_hblplayer_four_keeper_cost"),
    ]

    operations = [
        migrations.CreateModel(
            name="HBLTrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yahoo_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="HBLTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="hbl.hblplayer",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="hbl.hblteam",
                    ),
                ),
                (
                    "trade",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="hbl.hbltrade",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HBLAddPlayer",
            fields=[
                (
                    "hbltransaction_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="hbl.hbltransaction",
                    ),
                ),
                ("yahoo_id", models.IntegerField()),
                ("waiver", models.BooleanField(default=False)),
            ],
            bases=("hbl.hbltransaction",),
        ),
        migrations.CreateModel(
            name="HBLDropPlayer",
            fields=[
                (
                    "hbltransaction_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="hbl.hbltransaction",
                    ),
                ),
                ("yahoo_id", models.IntegerField()),
                (
                    "add",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dropped_for",
                        to="hbl.hbladdplayer",
                    ),
                ),
            ],
            bases=("hbl.hbltransaction",),
        ),
    ]
