# Generated by Django 4.1.7 on 2023-06-14 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hbl", "0006_hblplayer_four_keeper_cost"),
    ]

    operations = [
        migrations.CreateModel(
            name="HBLTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yahoo_id", models.IntegerField(null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("Add", "Add"), ("Drop", "Drop"), ("Trade", "Trade")],
                        default="Add",
                        max_length=5,
                    ),
                ),
                ("waiver", models.BooleanField(default=False)),
                ("date", models.DateField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "players",
                    models.ManyToManyField(
                        related_name="transactions", to="hbl.hblplayer"
                    ),
                ),
                (
                    "related_transaction",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corresponding_transaction",
                        to="hbl.hbltransaction",
                    ),
                ),
                (
                    "team",
                    models.ManyToManyField(
                        related_name="transactions", to="hbl.hblteam"
                    ),
                ),
            ],
        ),
    ]
